date_format: "%Y-%m-%d"

websites:
  - BOOKING
  - TRIPADVISOR
  - GOOGLE
  - EXPEDIA
  - HOLIDAYCHECK

hotels:
  - name: "Ananea Castelo Suites Hotel"
    aliases: ["ananea", "ananea castelo"]
    booking_url: "https://www.booking.com/hotel/pt/castelo-suites.en-gb.html"
    tripadvisor_location_id: "33299137"
    google_query: "Ananea Castelo Suites Algarve, Portugal"
    google_place_id: ""
    google_maps_url: "https://maps.app.goo.gl/QsTaS8vLupyrC3hQ8"
    expedia_url: "https://euro.expedia.net/Albufeira-Hotels-Castelo-Suites-Hotel.h111521689.Hotel-Information?pwaDialog=product-reviews"
    holidaycheck_url: "https://www.holidaycheck.de/hi/ananea-castelo-suites-algarve/069563af-47db-44a3-bdb1-3441ae3a2ac4"
    zoover_url: ""

  - name: "PortoBay Falésia"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/porto-bay-falesia.en-gb.html"
    tripadvisor_location_id: "625806"
    google_query: "PortoBay Falésia, Albufeira, Portugal"
    google_place_id: ""
    google_maps_url: "https://maps.app.goo.gl/DxodrUv4ub7qp89eA"
    expedia_url: "https://euro.expedia.net/Albufeira-Hotels-PortoBay-Falesia.h1787641.Hotel-Information?pwaDialog=product-reviews"
    holidaycheck_url: "https://www.holidaycheck.de/hi/portobay-falesia/44a47534-85c4-3114-a6da-472d82e16e29"
    zoover_url: ""

  - name: "Regency Salgados Hotel & Spa"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/regency-salgados-amp-spa.en-gb.html"
    tripadvisor_location_id: "23418643"
    google_query: "Regency Salgados Hotel & Spa, Algarve, Portugal"
    google_place_id: ""
    google_maps_url: "https://maps.app.goo.gl/UZ6dAot3VC4eWV3U7"
    expedia_url: "https://euro.expedia.net/Albufeira-Hotels-Regency-Salgados-Hotel-Spa.h67650702.Hotel-Information?pwaDialog=product-reviews"
    holidaycheck_url: "https://www.holidaycheck.de/hi/regency-salgados-hotel-spa/b0478236-7644-46b4-8fde-bd6cb1832cf8"
    zoover_url: ""

  - name: "NAU São Rafael Atlântico"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/sao-rafael-suites-all-inclusive.en-gb.html"
    tripadvisor_location_id: "289104"
    google_query: "NAU São Rafael Atlântico, Albufeira, Portugal"
    google_place_id: ""
    google_maps_url: "https://maps.app.goo.gl/G3Nfg49qBYQkR2xr5"
    expedia_url: "https://euro.expedia.net/Albufeira-Hotels-Sao-Rafael-Suite-Hotel.h1210300.Hotel-Information?pwaDialogNested=PropertyDetailsReviewsBreakdownDialog"
    holidaycheck_url: "https://www.holidaycheck.de/hi/nau-sao-rafael-suites-all-inclusive/739da55a-710e-3514-83f6-8e01149442a5"
    zoover_url: ""

  - name: "The Westin Salgados Beach Resort"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/westin-salgados-beach-resort-algarve.en-gb.html"
    tripadvisor_location_id: "1772673"
    google_query: "The Westin Salgados Beach Resort, Albufeira, Portugal"
    google_place_id: ""
    google_maps_url: "https://maps.app.goo.gl/CxCEgfZkiXnzAEsy9"
    expedia_url: "https://euro.expedia.net/Albufeira-Hotels-The-Westin-Salgados-Beach-Resort.h3639949.Hotel-Information?pwaDialog=product-reviews"
    holidaycheck_url: "https://www.holidaycheck.de/hi/the-westin-salgados-beach-resort-algarve/226cd009-8ddb-3e7f-8191-ca0e0024caf0"
    zoover_url: ""

  - name: "Vidamar Resort Hotel Algarve"
    aliases: []
    booking_url: "https://www.booking.com/hotel/pt/vidamar-algarve-hotel.en-gb.html"
    tripadvisor_location_id: "3927147"
    google_query: "Vidamar Resort Hotel Algarve, Albufeira, Portugal"
    google_place_id: ""
    google_maps_url: "https://maps.app.goo.gl/etAzqPDxgnjJ2DDu7"
    expedia_url: "https://euro.expedia.net/Albufeira-Hotels-VidaMar-Resort-Hotel-Algarve.h5670748.Hotel-Information?pwaDialog=product-reviews"
    holidaycheck_url: "https://www.holidaycheck.de/hi/vidamar-hotel-resort-algarve/e641bc1e-59d5-37a0-832e-90e6bbb51977"
    zoover_url: ""
